### ISSUE TITLE
Never asked for existing encryption passphrase, system stalls unless U2F key is connected

### ISSUE THREAD

**Issue by bigjdunham** [darkskiez/u2f-luks#2]
So after setting up this script, I am no longer asked for my existing encryption passphrase, instead my computer will not fully boot unless the U2F key is inserted and pressed at the right now. Is there a way to timeout waiting for the U2F key and then have it default back to my existing encryption passphrase if the U2F key is not connected?

**Comment by darkskiez** [comment]
I think you might be the first user other than me :)

I assume you are using the
* keyscript version: https://github.com/darkskiez/u2f-luks
(and not)
* the cryptsetup token plugin version: https://github.com/darkskiez/u2f-luks/tree/master/lukstoken

I've been recently working on the cryptsetup plugin one but I'll have to check the keyscript is still working as expected.

So the keyscript previously worked for me with a password prompt that falls back to passthrough to cryptsetup, so you could enter the password at the prompt OR tap a key. Because this is running in keyscript mode, timing out from a keyscript would unfortunately result in no password being returned to cryptsetup at all, it won't prompt by itself if a keyscript is supplied.

The token plugin one is a bit weird, cryptsetup prompts for a password and runs the token in the background which works, but then you need to press enter at the password prompt to continue anyway. Unfortunately this doesn't work with 2FA mode where you need a password to unlock the token, but this might work better for you depending on what you want.

(Its just occurred to me I could do a hybrid mode of keyscript AND token plugin to make that a lot more usable and consistent, but these are different implementations at the moment)

What exactly do you see when the system stalls on boot? maybe this interacts badly with some graphical boot thing. what distro/version?

**Comment by bigjdunham** [comment]
Yes I am using the keyscript version, and figured out the issue is that my distro's splash screen (Zorin OS 16) was not giving me the password prompt. When I turned off the splash screen I then was given the password prompt and it worked fine.
